name: Deploy ProPhone Landing

on:
  push:
    branches:
      - main

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy Repository to Server
        env:
          SSH_PASSWORD: ${{ secrets.IONOS_SERVER_KEY }}
        run: |
          sshpass -p $SSH_PASSWORD rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git' --exclude 'node_modules' --exclude 'venv' ./ root@${{ secrets.IONOS_SERVER_IP }}:/home/prophone-landing-repo

      - name: Deploy on Server
        env:
          SSH_PASSWORD: ${{ secrets.IONOS_SERVER_KEY }}
        run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no root@${{ secrets.IONOS_SERVER_IP }} << 'EOF'
            cd /home/prophone-landing-repo

            #remove unused docker files
            docker system prune -a -f

            # Build and run Backend Docker container
            docker build -t landing .
            docker stop landing || true
            docker rm landing || true
            docker run -d --name landing -p 3010:80 landing:latest
            
          EOF